"use client";

import "./globals.css";

import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Player from "@/components/Player/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en" className="flex items-center justify-center">
      <body className={[inter.className, "w-full md:w-[40vw]"]}>
        <header>
          <Navbar />
        </header>
        {children}
        <Player />
      </body>
    </html>
  );
}

export default RootLayout;
